#!/bin/bash

#Update Centos/7
sudo yum install -y epel-release
sudo yum update
sudo reboot

#Install java
sudo yum install -y java-1.8.0-openjdk.x86_64

#Install jenkins
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum install -y jenkins

#Start the jenkins service
sudo systemctl start jenkins.service

#Run the jenkins service at boot time
sudo systemctl enable jenkins.service
